applications/source/file-source/pom.xml, applications/stream-applications-core/common/stream-applications-composite-function-support/src/main/java/org/springframework/cloud/stream/app/composite/function/common/FunctionBindingEnvironmentPostProcessor.java, applications/stream-applications-core/common/stream-applications-composite-function-support/src/test/java/org/springframework/cloud/stream/app/composite/function/common/FunctionBindingsEnvironmentPostProcessorTests.java
Fixes #103 - excludes `splitter-function` from dependencies.  There may be some other sources that have the same issue. Also, includes changes to handle function composition with `,` or `|` delimiter
=> Fix file source

applications/processor/filter-processor/README.adoc, applications/processor/filter-processor/pom.xml, functions/function/filter-function/pom.xml, functions/function/filter-function/src/main/java/org/springframework/cloud/fn/filter/FilterFunctionConfiguration.java, functions/function/filter-function/src/main/java/org/springframework/cloud/fn/filter/FilterFunctionProperties.java, functions/function/filter-function/src/main/resources/application.properties, functions/function/filter-function/src/test/java/org/springframework/cloud/fn/filter/FilterFunctionApplicationTests.java
Fixes https://github.com/spring-cloud/stream-applications/issues/110
Turns out when functions are composed in the Spring Cloud Stream environment,
they are called via reactive wrappers which don't allow to emit `null` from the
`map()` operator.
* Make `filterFunction` fully reactive to reply on the `Flux.filter()` operator
* Add `config-common` for auto-conversion string configuration options into `Expression` instances
* Add `spring-boot-starter-json` dependency since it is required by the `SpelExpressionConverterConfiguration`
* Add `reactor-test` dependency to test the final solution
* Remove redundant dependencies from the `filter-processor`
=> GH-110: Fix filter function for emitting `null`

applications/stream-applications-core/pom.xml
- Add dependency for WF boot starter and s-c-sleuth-starter.
- Update the common app properties to include wf.application=${stream.name} and wf.service=${app.name}-${app.type}
- Update the common app properties to wf.tracing.enabled to false by default.
Related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/3967
=> Add WF tracing support

functions/common/file-common/src/main/java/org/springframework/cloud/fn/common/file/remote/RemoteFileRenamingAdvice.java, functions/supplier/sftp-supplier/pom.xml, functions/supplier/sftp-supplier/src/main/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierConfiguration.java, functions/supplier/sftp-supplier/src/main/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierProperties.java, functions/supplier/sftp-supplier/src/test/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierApplicationTests.java
Certain integration scenarios require moving remote files to a different path after processing, rather than deleting them.
This PR adds this capability to sftp-supplier through the new 'sftp-supplier.rename-remote-files-to' property, which a SpEl expression resolving to the new name of the file at hand.
=> sftp-supplier: renaming remote files after processing

functions/supplier/jms-supplier/src/main/java/org/springframework/cloud/fn/supplier/jms/JmsSupplierConfiguration.java, functions/supplier/mail-supplier/src/main/java/org/springframework/cloud/fn/supplier/mail/MailSupplierConfiguration.java, functions/supplier/mqtt-supplier/src/main/java/org/springframework/cloud/fn/supplier/mqtt/MqttSupplierConfiguration.java, functions/supplier/syslog-supplier/src/main/java/org/springframework/cloud/fn/supplier/syslog/SyslogSupplierConfiguration.java, functions/supplier/twitter-supplier/src/main/java/org/springframework/cloud/fn/supplier/twitter/status/stream/TwitterStreamSupplierConfiguration.java, functions/supplier/websocket-supplier/src/main/java/org/springframework/cloud/fn/supplier/websocket/WebsocketSupplierConfiguration.java
Redesigning suppliers that use reactive output channel name as
the literal "output" explicitly, as this  cuases some conflicts
with the output channel name usage in Spring Cloud Stream.
The fix is done either by simply renaming the channel name
or by avoid using it directly, but delegate its use through the SI Java DSL.
Resolves https://github.com/spring-cloud/stream-applications/issues/160
=> Refactor the usage of output channel in suppliers

applications/stream-applications-core/pom.xml
- Add the spring-cloud-sleuth-zipkin dependency to allow the streaming apps to send their distributed traces to Zipkin Servers.
- Disable the Zipkin Server trace sending by default (spring.zipkin.enabled=false).
=> Add support for Zipkin Server trace collection

applications/stream-applications-core/stream-applications-security-common/src/test/java/org/springframework/cloud/stream/app/security/common/ReactiveSecurityEnabledManagementSecurityEnabledTests.java, applications/stream-applications-core/stream-applications-security-common/src/test/java/org/springframework/cloud/stream/app/security/common/SecurityEnabledManagementSecurityEnabledTests.java
Related to: https://github.com/spring-cloud/stream-applications/issues/171
The `/info` is not unsecured any more starting with Spring Boot `2.5`:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#secure-info-endpoint
=> GH-171: Fix security tests for actuator endpoints

applications/source/cdc-debezium-source/pom.xml
Not sure why this is necessary, but without this, maven overrides to a later version for some reason. Note, the `cdc-debezium-supplier` dependencies are already show the desired version.
=> Fix mysql-connector-java managed dependency

applications/source/cdc-debezium-source/src/test/java/org/springframework/cloud/stream/app/source/cdc/CdcMySqlTestSupport.java
Latest jdk8#301 disables TLS 1.0/1.1 used by default by the not up-to-date mysql jdbc connectors.
This leads to errors like this: `javax.net.ssl.SSLHandshakeException:No appropriate protocol`.
A workaround is to set the enabledTLSProtocols=TLSv1.2 jdbc url parameter explicitly.
=> Fix mysql compatibility with jdk8_301

applications/stream-applications-core/stream-applications-security-common/src/main/java/org/springframework/cloud/stream/app/security/common/AppStarterWebFluxSecurityAutoConfiguration.java, applications/stream-applications-core/stream-applications-security-common/src/main/java/org/springframework/cloud/stream/app/security/common/AppStarterWebSecurityAutoConfiguration.java, applications/stream-applications-core/stream-applications-security-common/src/test/java/org/springframework/cloud/stream/app/security/common/ReactiveSecurityEnabledManagementSecurityEnabledTests.java, applications/stream-applications-core/stream-applications-security-common/src/test/java/org/springframework/cloud/stream/app/security/common/SecurityEnabledManagementSecurityEnabledTests.java
This will expose the root `/actuator` endpoint if `management.endpoints.web.discovery.enabled=true`. There is another PR on the apps generator plugin to set the property to true by default.
=> Enable actuator discovery

functions/common/mqtt-common/pom.xml, functions/common/mqtt-common/src/main/java/org/springframework/cloud/fn/common/mqtt/MqttConfiguration.java, functions/common/mqtt-common/src/main/java/org/springframework/cloud/fn/common/mqtt/MqttProperties.java, functions/consumer/mqtt-consumer/README.adoc, functions/consumer/mqtt-consumer/src/test/java/org/springframework/cloud/fn/consumer/mqtt/MqttConsumerTests.java, functions/supplier/mqtt-supplier/README.adoc, functions/supplier/mqtt-supplier/src/test/java/org/springframework/cloud/fn/supplier/mqtt/MqttSupplierTests.java
Fixes https://github.com/spring-cloud/stream-applications/issues/183
* Add `MqttProperties.sslProperties` common MQTT configuration property as a `Map` structure
* Delegate a content fo the `MqttProperties.sslProperties` into `mqttConnectOptions.setSSLProperties()`
in the common `MqttConfiguration`
* Verify that SSL properties are applied in both `MqttSupplierTests` & `MqttConsumerTests`
* Document a new `MqttProperties.sslProperties` configuration property for both consumer and supplier
* Use `eclipse-mosquitto` Docker image for MQTT tests instead of RabbitMQ plugin: the Mosquitto starts much faster
=> GH-183: Expose MQTT SSL properties

applications/sink/mqtt-sink/README.adoc, applications/source/cdc-debezium-source/pom.xml, applications/source/cdc-debezium-source/src/test/java/org/springframework/cloud/stream/app/source/cdc/CdcFlatteningIntegrationTest.java, applications/source/cdc-debezium-source/src/test/java/org/springframework/cloud/stream/app/source/cdc/CdcMySqlTestSupport.java, applications/source/cdc-debezium-source/src/test/java/org/springframework/cloud/stream/app/source/cdc/CdcSourceDatabasesIntegrationTest.java, applications/source/cdc-debezium-source/src/test/resources/json/mysql_insert_inventory_products_106.json, applications/source/mqtt-source/README.adoc, functions/common/cdc-debezium-boot-starter/pom.xml, functions/common/cdc-debezium-boot-starter/src/test/java/org/springframework/cloud/fn/common/cdc/CdcBootStarterIntegrationTest.java, functions/common/cdc-debezium-common/pom.xml, functions/common/cdc-debezium-common/src/main/java/org/springframework/cloud/fn/common/cdc/EmbeddedEngine.java, functions/consumer/mqtt-consumer/src/test/java/org/springframework/cloud/fn/consumer/mqtt/MqttConsumerTests.java, functions/supplier/cdc-debezium-supplier/pom.xml, functions/supplier/mqtt-supplier/src/test/java/org/springframework/cloud/fn/supplier/mqtt/MqttSupplierTests.java
Fixes https://github.com/spring-cloud/stream-applications/issues/182
* Upgrade Debezium dependency to 1.7.1
* Remove explicit dependencies for DBs and remove excludes for them from Debezium deps;
rely fully on whatever Debezium connectors bring for us
* Fix `EmbeddedEngine` for compatibility with the Debezium 1.7.1
* Fix CDC tests for the current state of Debezium results
* Fix Checkstyle violations in the MQTT modules
=> GH-182: Upgrade Debezium to 1.7.1

functions/supplier/file-supplier/src/main/java/org/springframework/cloud/fn/supplier/file/FileSupplierConfiguration.java, functions/supplier/file-supplier/src/test/java/org/springframework/cloud/fn/supplier/file/DefaultFileSupplierTests.java
SO: https://stackoverflow.com/questions/69802199/how-to-use-watchservicedirectoryscanner-with-spring-cloud-stream-file-supplier
The `FileReadingMessageSource` has to be started if `useWatchService()` is used.
=> Fix File Supplier for lifecycle

functions/supplier/http-supplier/README.adoc, functions/supplier/http-supplier/src/main/java/org/springframework/cloud/fn/supplier/http/HttpSupplierConfiguration.java, functions/supplier/http-supplier/src/test/java/org/springframework/cloud/fn/supplier/http/HttpSupplierApplicationTests.java
Fixes https://github.com/spring-cloud/stream-applications/issues/207
When no HTTP `Content-Type` header, the NPE is thrown from the `enrichHeaders()`
endpoint
* Fix NPE extracting header value via `get(MessageHeaders.CONTENT_TYPE, MediaType.class)`
* Make `httpHeaderMapper` bean as a `@ConditionalOnMissingBean` to let end-users
to provide their own custom `HeaderMapper<HttpHeaders>`
* Move `httpSupplierProperties.getMappedRequestHeaders()` setting to the `httpHeaderMapper` bean
* Use `httpHeaderMapper` bean injection into the `WebFlux.inboundChannelAdapter()` instead of
just `httpSupplierProperties.getMappedRequestHeaders()`
* Mention custom `HeaderMapper<HttpHeaders>` in the README
=> GH-207: Fix NPE in the HttpSupplierConfiguration

functions/function/aggregator-function/src/main/java/org/springframework/cloud/fn/aggregator/AggregatorFunctionConfiguration.java
The `aggregatorFunction` has a flaw subscribing and emitting
data from a source `Flux` too early: from a `doOnSubscribe()`
callback which is really called *before* the real subscription is
registered in the target `Publisher`
Change the logic to the `doOnRequest()` which happens already
after subscription is registered in the `Publisher`
**Cherry-pick to `2020.0.x`**
=> Change `doOnSubscribe` to `doOnRequest`

applications/processor/script-processor/src/test/java/org/springframework/cloud/stream/app/processor/script/ScriptProcessorIntegrationTests.java, applications/sink/redis-sink/pom.xml, applications/sink/redis-sink/src/test/java/org/springframework/cloud/stream/app/sink/redis/RedisSinkTests.java, applications/sink/tcp-sink/src/test/java/org/springframework/cloud/stream/app/sink/tcp/TcpSinkTests.java, applications/sink/websocket-sink/src/test/java/org/springframework/cloud/stream/app/websocket/sink/WebsocketSinkTests.java, applications/source/twitter-search-source/src/test/java/org/springframework/cloud/stream/app/source/twitter/search/TwitterSearchSourceIntegrationTests.java, applications/stream-applications-core/pom.xml, functions/consumer/redis-consumer/pom.xml, functions/consumer/tcp-consumer/src/main/java/org/springframework/cloud/fn/consumer/tcp/TcpConsumerConfiguration.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/CRLFTests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/L1Tests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/L2Tests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/L4Tests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/LFTests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/NULLTests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/NotNioTests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/PropertiesPopulatedTests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/RAWTests.java, functions/consumer/tcp-consumer/src/test/java/org/springframework/cloud/fn/consumer/tcp/STXETXTests.java, functions/consumer/websocket-consumer/src/main/java/org/springframework/cloud/fn/consumer/websocket/WebsocketConsumerConfiguration.java, functions/consumer/websocket-consumer/src/main/java/org/springframework/cloud/fn/consumer/websocket/WebsocketConsumerServer.java, functions/consumer/websocket-consumer/src/test/java/org/springframework/cloud/fn/consumer/websocket/WebsocketConsumerTests.java, functions/supplier/mongodb-supplier/src/test/java/org/springframework/cloud/fn/supplier/mongo/MongodbSupplierApplicationTests.java, functions/supplier/twitter-supplier/src/main/java/org/springframework/cloud/fn/supplier/twitter/status/search/TwitterSearchSupplierConfiguration.java, stream-applications-build/pom.xml
I will comment inline where appropriate. 
This fixes all previously disabled tests except the security ones which are being handled in @dturanski [code proposal](https://github.com/spring-cloud/stream-applications/pull/212).
Also, @artembilan I went ahead and kept the MongoDB tests in this PR. If you are ok w/ that we can close https://github.com/spring-cloud/stream-applications/pull/211.
=> Re-enable and fix tests that were failing w/ Boot 2.6 upgrade.

applications/sink/rabbit-sink/src/test/java/org/springframework/cloud/stream/app/sink/rabbit/OwnConnectionTest.java, applications/source/rabbit-source/src/test/java/org/springframework/cloud/stream/app/source/rabbit/RabbitSourceListenerTests.java, functions/consumer/rabbit-consumer/src/main/java/org/springframework/cloud/fn/consumer/rabbit/RabbitConsumerConfiguration.java, functions/supplier/rabbit-supplier/src/main/java/org/springframework/cloud/fn/supplier/rabbit/RabbitSupplierConfiguration.java
This code proposal breaks the dependence on [RabbitAutoConfiguration](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/187#issuecomment-860227374) for the `rabbit-consumer` and `rabbit-supplier` functions.
=> Break dependence on RabbitAutoConfiguration

applications/processor/script-processor/pom.xml, applications/stream-applications-core/pom.xml
The `Jython` doesn't work in the uber jar as a nested one.
The Spring Boot provides a trick via unpacking requested nested jars.
* Use the latest `spring-cloud-dataflow-apps-generator-plugin` which allows now
to propagate a custom configuration for `spring-boot-maven-plugin`
* Add `requiresUnpack` for `jython-standalone` into the `script-processor`
**Cherry-pick to 2021.1.x**
=> Add requiresUnpack for script-processor

applications/stream-applications-core/pom.xml
We will remove this disablement once the underlying Spring Cloud Sleuth issue is addressed. 
Manually verified this fixes the failing ITs w/ these steps:
- Execute the IT in IDEA and watch it ❌ 
- Execute the following commands:
```bash
./mvnw clean install -f applications/stream-applications-core
./mvnw clean package -pl :http-request-processor
cd applications/processor/http-request-processor/apps/http-request-processor-kafka
./mvnw clean install jib:dockerBuild
```
- Execute the IT in IDEA and watch is ✅ 
Reference SCS issue here
=> Disable Spring Cloud Sleuth function instrumentation

applications/source/jdbc-source/src/main/resources/application.properties, applications/stream-applications-integration-tests/src/test/java/org/springframework/cloud/stream/app/integration/test/stream/jdbclog/KafkaJdbcLogStreamTests.java
Fixes IT failure KafkaJdbcLogStreamTests
The `jdbc-source-kafka` is failing to properly start. It is attempting to determine the DB platform type from an actual connection but the DB is not yet up. This is due to the rework of DB init scripts in 2.6 ([bug outlined here](https://github.com/spring-projects/spring-boot/issues/28897)).
~This sets `spring.integration.jdbc.platform=mysql` to specify the platform.~
This now uses `@Nested` to wait for the outer `@Container` to start.
=> Set spring.integration.jdbc.platform in jdbc-sink app

src/main/groovy/org/springframework/jenkins/stream/applications/ci/StreamApplicationsBuildMaker.groovy
* Add branch tag to docker image for all builds
* Add 'latest' tag to docker image for main branch build
* Run ITs against specific branch docker image
This coupled w/ the changes in 
- https://github.com/spring-cloud/spring-cloud-dataflow-apps-plugin/pull/12 
- https://github.com/spring-cloud/stream-applications/pull/230
should make things work smoothly.
=> Make docker image tags and IT usage of those tags more explicit

applications/source/load-generator-source/pom.xml
The `load-generator-source` does not generate a proper name for the function bean.
Use an explicit `<functionDefinition>loadGeneratorSupplier</functionDefinition>`
since the `<name>load-generator</name>` is not cameCase-compatible with
existing `loadGeneratorSupplier` bean name
**Cherry-pick to `2021.1.x`**
=> Add functionDefinition=loadGeneratorSupplier

stream-applications-release-train/stream-applications-descriptor/src/main/resources/META-INF/kafka-apps-maven.properties
Fixes the following:
The following error is thrown when SCDF attempts to auto-import the Kafka apps. 
```
dataflow-server             | java.lang.IllegalArgumentException: Bad artifact coordinates org.springframework.cloud.stream.app:cdc-debezium-source-kafka:jar:metadata::3.2.0, expected format is <groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>
dataflow-server             | 	at org.springframework.util.Assert.isTrue(Assert.java:121)
[11:42](https://vmware.slack.com/archives/D02UXPU2EJV/p1646415744809939)
```
Steps to reproduce:
```
wget -O docker-compose.yml https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.10.0-M1/src/docker-compose/docker-compose.yml
DATAFLOW_VERSION=2.10.0-M1 SKIPPER_VERSION=2.9.0-M1 docker-compose up
```
=> Fix auto-import of Kafka apps in SCDF

applications/source/file-source/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties, applications/source/file-source/src/main/resources/META-INF/dataflow-configuration-metadata.properties, functions/supplier/file-supplier/pom.xml, functions/supplier/file-supplier/src/main/java/org/springframework/cloud/fn/supplier/file/FileSupplierConfiguration.java, functions/supplier/file-supplier/src/test/java/org/springframework/cloud/fn/supplier/file/DefaultFileSupplierTests.java, functions/supplier/s3-supplier/README.adoc
Fixes https://github.com/spring-cloud/stream-applications/issues/249
Currently, the metadata store is supported by remote files source (S3, ftp and sftp), but not by file source.
There are cases where it is convenient to be able to use the metadata store with file source as well.
* Add externally configured `ConcurrentMetadataStore` into `FileSupplierConfiguration`
which is based on the auto-configuration provided by the `metadata-store-common` artifact
* Test with an embedded JDBC store
* Remove redundant dependencies in the file-supplier pom - supplied by the parent
* Add `MetadataStoreProperties` to allow-list for dataflow
* Fix typo in the `s3-supplier` README
=> GH-249: Add metadata-store to file-supplier

functions/common/config-common/pom.xml, functions/common/config-common/src/main/java/org/springframework/cloud/fn/common/config/ComponentCustomizationAutoConfiguration.java
The [CI build was failing](https://jenkins.spring.io/job/stream-applications-java-functions-main-ci/805/console) w/ 
```java
Downloaded from spring-releases: https://repo.spring.io/release/org/springframework/security/spring-security-bom/5.6.5/spring-security-bom-5.6.5.pom (5.7 kB at 11 kB/s)
Downloading from tensorflow-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/springframework/cloud/stream/app/stream-applications-build/1.2.1-SNAPSHOT/maven-metadata.xml
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] 'dependencies.dependency. org.springframework.cloud.fn:config-common:1.2.1-SNAPSHOT' for org.springframework.cloud.fn:config-common:1.2.1-SNAPSHOT is referencing itself. @ …
```
=> Fix circular dependency and checkstyle in config-common

functions/consumer/jdbc-consumer/src/main/resources/application.properties, functions/function/http-request-function/src/main/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionConfiguration.java, functions/supplier/jdbc-supplier/src/main/resources/application.properties, functions/supplier/jdbc-supplier/src/test/java/org/springframework/cloud/fn/supplier/jdbc/DefaultJdbcSupplierTests.java, functions/supplier/mail-supplier/src/main/java/org/springframework/cloud/fn/supplier/mail/MailSupplierConfiguration.java
The `IntegrationAutoConfiguration` provides mechanism to initialize DB with some out-of-the-box scripts. The default behavior is `EMBEDDED` even if we don't use any components for those DB objects, e.g. no `JdbcMessageStore` bean.
* Add `spring.integration.jdbc.initialize-schema=NEVER` to the `jdbc-consumer` and `jdbc-supplier` to not attempt to initialize DB
* Fix Checkstyle violations in other modules
=> Disable DB init for JDBC Source and Sink

functions/consumer/sftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerSessionFactoryConfiguration.java, functions/supplier/sftp-supplier/src/main/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierFactoryConfiguration.java
Fixes https://github.com/spring-cloud/stream-applications/issues/348
Currently, SFTP modules use a `FileSystemResource` based on a resolved from knownHostsExpression.
This is not always true since the resource could be anywhere, not only in the target file system.
The typical use-use is classpath or Secretes on the target platform
* Use `DefaultResourceLoader` to resolve a location from the expression to any possible `Resource` impl
=> GH-348: Resolve knownHostsExpression to Resource

applications/processor/header-enricher-processor/src/test/java/org/springframework/cloud/stream/app/processor/header/enricher/HeaderEnricherProcessorTests.java, functions/function/header-enricher-function/src/main/java/org/springframework/cloud/fn/header/enricher/HeaderEnricherFunctionConfiguration.java, functions/function/header-enricher-function/src/test/java/org/springframework/cloud/fn/header/enricher/HeaderEnricherFunctionApplicationTests.java
Fixes https://github.com/spring-cloud/stream-applications/issues/369
Spring Boot `@AutoConfiguration` comes now with a `proxyBeanMethods = false`, so we cannot call bean methods within the same configuration class
* Rework `HeaderEnricherFunctionConfiguration` for bean methods autowiring
* Create an `ExpressionEvaluatingHeaderValueMessageProcessor` instances directly in the `headerEnricher` bean definition and propagate an injected `BeanFactory`
=> GH-369: Fix HeaderEnricher for no proxyBeanMethod

stream-applications-build/pom.xml
Locking onto RC for SB/SC as they are firming up and approaching full release. 
Creating PR only for visibility that we are making this change.
=> Update to Spring Boot 3.0.0-RC2 / Spring Cloud 2022.0.0-RC1

.github/workflows/ci-pr.yml, .github/workflows/common.yml, applications/processor/script-processor/pom.xml, applications/processor/script-processor/src/test/java/org/springframework/cloud/stream/app/processor/script/ScriptProcessorIntegrationTests.java, etc/checkstyle/checkstyle.xml
Fixes https://github.com/spring-cloud/stream-applications/issues/370
* Update dependencies for `script-processor`
* Add `maven-surefire-plugin` to `script-processor` POM and specify `--add-opens` for Ruby requirements
* Mark all JavaScript tests with `@EnabledIfSystemProperty` against `org.graalvm.language.js.home` which is available only if GraalVM with `js` component enabled
* Fix `NewlineAtEndOfFile` rule for Checkstyle since on Windows the line end is `crlf`
* Add `components: 'js'` to GraalVM installation steps for all the GH action scripts
=> GH-370: Enable ScriptProcessor tests back

applications/sink/router-sink/README.adoc, applications/sink/router-sink/src/main/java/org/springframework/cloud/stream/app/sink/router/BindingChannelResolver.java, applications/sink/router-sink/src/main/java/org/springframework/cloud/stream/app/sink/router/RouterSinkConfiguration.java, applications/sink/router-sink/src/main/java/org/springframework/cloud/stream/app/sink/router/RouterSinkProperties.java, applications/sink/router-sink/src/test/java/org/springframework/cloud/stream/app/sink/router/RouterSinkIntegrationTests.java, applications/sink/router-sink/src/test/resources/routertest.groovy, stream-applications-build/pom.xml
Fixes https://github.com/spring-cloud/stream-applications/issues/330
The `BinderAwareChannelResolver` is removed now from SCST.
* Rework the router sink application logic to rely on a `StreamBridge` from SCST. For the reason introduce a simple `BindingChannelResolver` which creates path-through `MessageChannel` proxy for `streamBridge.send()` API and caches such a channel for future calls. This way the router logic from Spring Integration remains the same: we resolve a key into specific `MessageChannel`.
* Use `resolutionRequired` in this `BindingChannelResolver` to determine if binding has been declared explicitly for the application.
* Rename `defaultOutputChannel` configuration property into `defaultOutputBinding` since router sink does not rely on channel anymore, but rather on …
=> GH-330: Rework Router Sink for `StreamBridge`

functions/supplier/s3-supplier/src/main/java/org/springframework/cloud/fn/supplier/s3/AwsS3SupplierConfiguration.java, functions/supplier/s3-supplier/src/test/java/org/springframework/cloud/fn/supplier/s3/AbstractAwsS3SupplierMockTests.java, functions/supplier/s3-supplier/src/test/java/org/springframework/cloud/fn/supplier/s3/AmazonS3FilesTransferredTests.java, functions/supplier/s3-supplier/src/test/java/org/springframework/cloud/fn/supplier/s3/AmazonS3LinesTransferredTests.java, functions/supplier/s3-supplier/src/test/java/org/springframework/cloud/fn/supplier/s3/AmazonS3ListOnlyTests.java
Fixes https://github.com/spring-cloud/stream-applications/issues/431
* Use `WatchService` for local file `MessageSource` in `AwsS3SupplierConfiguration` for `S3InboundFileSynchronizingMessageSource`.
This way we are able to scan sub-dirs in the local file store and skip those sub-dirs as entities.
The `S3InboundFileSynchronizingMessageSource` is able to properly create a local sub-dir according to the complex key of S3 object, for example if we have a remove entry as `myDir/myFile.txt`, so in the `/local` dir it will be stored as `/local/myDir/myFile.txt`. The mentioned `WatchService` can react to entries of entire file tree.
=> GH-431: Support sub-dirs in S3 Source

functions/supplier/sftp-supplier/README.adoc
* Highlight the `ref` mode invalid when streaming
* Use properties rather than shell options in docs
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5225
=> Clarify sftp-supplier docs

applications/processor/aggregator-processor/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties, applications/processor/aggregator-processor/src/main/resources/META-INF/dataflow-configuration-metadata.properties, applications/sink/elasticsearch-sink/README.adoc, applications/sink/elasticsearch-sink/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties, applications/sink/elasticsearch-sink/src/main/resources/META-INF/dataflow-configuration-metadata.properties, applications/source/mail-source/README.adoc
* `sink/elasticsearch-sink`: SB3 now uses Elastic Java client instead of Elastic High-Level REST client, therefore replace `ElasticsearchRestClientProperties` w/ `ElasticsearchProperties.
* `processor/aggregator-processor`: SB3 has removed Embedded Mongo support, therefore remove the corresponding EmbeddedMongoProperties.
Fixes #435
=> Remove invalid config props references

applications/sink/elasticsearch-sink/src/test/java/org/springframework/cloud/stream/app/sink/elasticsearch/ElasticsearchSinkTests.java, applications/sink/elasticsearch-sink/src/test/resources/logback-test.xml, functions/consumer/elasticsearch-consumer/src/main/java/org/springframework/cloud/fn/consumer/elasticsearch/ElasticsearchConsumerConfiguration.java
- Use `Consumer<Message<?>>` on IntegrationFlow rather than `Consumer`
Fixes #440
=> Fix ElasticsearchSink index name header

applications/stream-applications-core/pom.xml
- add back in Prometheus Rsocket proxy dep
- rename `managment.metrics.export` properties
=> Fix metrics export for Spring Boot 3.x

applications/source/debezium-source/README.adoc, applications/source/debezium-source/src/test/java/org/springframework/cloud/stream/app/source/debezium/integration/DebeziumSupplierAvroFormatTest.java, functions/supplier/debezium-supplier/src/main/java/org/springframework/cloud/fn/supplier/debezium/DebeziumEngineBuilderAutoConfiguration.java, functions/supplier/debezium-supplier/src/main/java/org/springframework/cloud/fn/supplier/debezium/DebeziumProperties.java, functions/supplier/debezium-supplier/src/main/java/org/springframework/cloud/fn/supplier/debezium/DebeziumReactiveConsumerConfiguration.java, functions/supplier/debezium-supplier/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, functions/supplier/debezium-supplier/src/test/java/org/springframework/cloud/fn/supplier/debezium/DebeziumEngineBuilderAutoConfigurationTests.java, functions/supplier/debezium-supplier/src/test/java/org/springframework/cloud/fn/supplier/debezium/DebeziumPropertiesTests.java, functions/supplier/debezium-supplier/src/test/java/org/springframework/cloud/fn/supplier/debezium/custom/DebeziumEngineBuilderAutoConfigurationTest.java, functions/supplier/debezium-supplier/src/test/java/org/springframework/cloud/fn/supplier/debezium/it/TestJdbcTemplateConfiguration.java, functions/supplier/debezium-supplier/src/test/java/org/springframework/cloud/fn/supplier/debezium/it/custom/DebeziumEngineBuilderAutoConfigurationIntegrationTest.java, functions/supplier/debezium-supplier/src/test/java/org/springframework/cloud/fn/supplier/debezium/it/custom/EmbeddedEngineExecutorService.java, functions/supplier/debezium-supplier/src/test/java/org/springframework/cloud/fn/supplier/debezium/it/supplier/DebeziumSupplierIntegrationTest.java
- Rename DebeziumEngineAutoConfiguration into DebeziumEngineBuilderAutoConfiguration.
- Make the DebeziumEngineBuilderAutoConfiguration auto-create a DebeizumEngine.Builder instance.
- Move the DebeizumEngine bean creation to the DebeziumReactiveConsumerConfiguration.
- Make DebeziumEngineBuilderAutoConfiguration conditional on Debeizum connecgtor on the class path and debezium.properties.connector.class property set.
- Minor improvment on the serialization format class resolution.
- Add support for debezium header serialization format, required for the change event headers to work.
Resolves #458
=> Factor out the Debezium Engine Builder auto-configuration

applications/processor/aggregator-processor/README.adoc, applications/processor/aggregator-processor/pom.xml, applications/processor/aggregator-processor/src/test/java/org/springframework/cloud/fn/aggregator/AggregatorProcessorTests.java, functions/function/aggregator-function/pom.xml, functions/function/payload-converter-function/src/main/java/functions/JsonBytesToMap.java
Fixes https://github.com/spring-cloud/stream-applications/issues/441
* Introduce a `JsonBytesToMap` as a part of a `payload-converter-function` module which is auto-discovered by Spring Cloud Function scanning algorithm - the `functions` package.
* Add a `payload-converter-function` as dependency into an `aggregator-function`
* Compose `jsonBytesToMap|aggregatorFunction` for the `aggregator-processor`
* Verify a `JsonBytesToMap` function in action with an `AggregatorProcessorTests`
* Mentioned such a payload conversion in the `aggregator-processor` README
=> GH-441: Add `JsonBytesToMap` function

applications/source/debezium-source/pom.xml, applications/source/debezium-source/src/test/java/org/springframework/cloud/stream/app/source/debezium/databases/DebeziumDatabasesIntegrationTest.java, applications/source/debezium-source/src/test/java/org/springframework/cloud/stream/app/source/debezium/integration/TestDebeziumSourceApplication.java, applications/stream-applications-core/pom.xml
Provide auto-config application support. 
Requires `org.springframework.cloud:spring-cloud-dataflow-apps-generator-plugin` version >= 1.0.8-SNAPSHOT.
=> [DO NOT MERGE YET] app auto-conf support

functions/function/aggregator-function/src/main/java/org/springframework/cloud/fn/aggregator/AggregatorFunctionConfiguration.java, functions/function/aggregator-function/src/test/java/org/springframework/cloud/fn/aggregator/RedisMessageStoreAggregatorTests.java
Fixes https://github.com/spring-cloud/stream-applications/issues/500
When `listeners` are provided for `DefaultKafkaConsumerFactory`, the target `KafkaConsumer` instance is proxied.
The `java.lang.reflect.Proxy` is `Serializable`,
but the value it is wrapping is not.
When the `MessageHeaders` is serialized (e.g. into persistent `MessageStore`), it checks for `Serializable` type only on top-level object of the header. Therefore, the `Proxy` is passing condition, but eventually we fail with `NotSerializableException`, since the proxied object is not like that
* Remove `kafka_consumer` from a message before it reaches an aggregator with its logic to serialize message into the store
This is a workaround until Spring for Apache Kafka is released with the fix: …
=> GH-500: Workaround for non-serializable header

README.adoc
I recently came across the "Task Launcher" link in the README.doc of your repository. Upon further inspection, I noticed that the link does not lead to a functioning page, and there doesn't appear to be any associated functionality.
Considering this, I kindly request that you consider removing the non-functional link from the README.doc to avoid any confusion for future visitors to your repository. 
Thank you for your attention to this matter, and please let me know if you have any questions or require any assistance.
Best regards, SeungJin Jeong.
=> Request to Remove Non-functional Link in README.doc

functions/consumer/ftp-consumer/pom.xml, functions/consumer/sftp-consumer/pom.xml
I noticed unexpected logging behaviour when using `sftp-consumer` caused by the missing test scope of the `function-test-support` dependency.
Workaround:
```
<dependency>
<groupId>org.springframework.cloud.fn</groupId>
<artifactId>sftp-consumer</artifactId>
<version>4.0.1-SNAPSHOT</version>
<exclusions>
<exclusion>
<groupId>org.springframework.cloud.fn</groupId>
<artifactId>function-test-support</artifactId>
</exclusion>
</exclusions>
</dependency>
```
=> Fix scope of function-test-support dependency

applications/stream-applications-core/stream-applications-security-common/src/test/resources/META-INF/spring.binders
Works around issue in SCSt `4.1.2` where the spring.binders was removed from the 
`spring-cloud-stream-test-binder` module.
cc: @sobychacko
=> Add spring.binders for SCSt test binder

spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-metadata-plugin/src/main/java/org/springframework/cloud/dataflow/app/plugin/MetadataAggregationMojo.java
The metadata plugin currently barfs when it encounters a config item with an enum field that references itself (e.g. `JdbcDatabaseDialect`). This commit allows processing to continue when the bad enums are encountered.
=> [Apps Plugin] Allow bad enum constants

README.adoc, applications/stream-applications-core/pom.xml, full-build-no-test.sh
This PR adds the required dependencies for Micrometer Tracing with the Brave bridge
with the ability to report trace to Zipkin or Wavefront. 
Also the following unrelated commits are piggybacking:
- covenience script to do a full build w/o tests
- update to Prometheus Rsocket 2.0.0-M1
> [!IMPORTANT]
> During merge please keep the commits separate as they are unrelated
=> Add Micrometer tracing

applications/stream-applications-core/pom.xml
The previous commit for adding Tracing attempted to use dependency management for the `prometheus-rsocket-spring` lib in the generated applications pom.xml. However, the app generator plugin assumes the dep mgmt is for a POM and adds tags for this which fails at runtime.
This commit removes the dep. mgmt. for `prometheus-rsocket-spring` and instead specifies the version on the dependency.
Also, the tracing property for Wavefront and Zipkin are updated.
=> Fix dependency mgmt in generated apps pom.xml

applications/stream-applications-core/pom.xml, clean-apps.sh, spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/resources/unit/http-source-apps/pom.xml
This updates the SCS starter to v4.1.5 and java-cfenv-boot version to v3.2.0 to properly support Boot 3.3.x.
Resolves #550
=> Update SCS starter

.github/workflows/ci-pr.yml, build-app.sh, build-apps.sh, build-core.sh, build-folder.sh, local/pack-containers.sh
Removed checks for changed modules and ensure the build scripts works in the absence of credentials. This changes the distribution to use liberica since it properly detects the latest patch version of the distribution.
See #550
=> Simplify CI-PR

.github/workflows/common.yml
Add a flag named `enableSecurityScan` to manage execution of trivy scan that will be `false` by default.
=> Disable Trivy Scan by default

applications/sink/redis-sink/src/test/java/org/springframework/cloud/stream/app/sink/redis/RedisSinkTests.java, applications/sink/s3-sink/README.adoc, applications/source/jms-source/README.adoc, applications/source/s3-source/README.adoc, applications/stream-applications-core/pom.xml, clean-apps.sh, functions/common/function-test-support/pom.xml, functions/consumer/s3-consumer/src/test/java/org/springframework/cloud/fn/consumer/s3/AbstractAwsS3ConsumerMockTests.java, functions/consumer/s3-consumer/src/test/java/org/springframework/cloud/fn/consumer/s3/AmazonS3UploadFileTests.java, functions/consumer/s3-consumer/src/test/java/org/springframework/cloud/fn/consumer/s3/AmazonS3UploadInputStreamTests.java, stream-applications-build/pom.xml
> [!NOTE]
> This encompasses several related, yet explicitly separated w/ their own commit messages, commits. Please, whoever merges this do a REBASE rather than SQUASH. Please and ty.
This PR updates various dependencies to the latest patch versions as follows:
- spring-boot to 3.1.12
- spring-framework to 6.0.21
- spring-integration-aws to 3.0.2
- spring-cloud to 2022.0.5
- spring-cloud-aws to 3.0.2
- spring-kafka to 6.0.21
- spring-amqp to 3.0.14
- org.apache.sshd:sshd-sftp to 2.9.3
Quite a few things had to happen along the way to make the above work. See commit messages for details
=> Update various dependencies patch versions (2022.0.x)

applications/stream-applications-core/pom.xml
Set spring.cloud.bootstrap.enabled=true by default which allows the containers for the ITs to properly start.
=> Set spring.cloud.bootstrap.enabled=true by default

.github/actions/install-trivy/action.yml, applications/processor/header-filter-processor/src/test/java/org/springframework/cloud/stream/app/processor/header/filter/HeaderFilterProcessorTests.java, applications/stream-applications-core/pom.xml, scan-folders.sh, stream-applications-build/pom.xml
Updates Spring Functions Catalog to 5.0.1
Updates Spring Boot to 3.3.6
Updates RabbitMQ Http Client to 5.2.0
Updates NoHttp Checkstyle to 0.0.11
Updates Spring Java Format Checkstyle to 0.0.43
Updates Spring Framework to 6.1.15
Updates Spring Cloud Release Train to 2023.0.4
Updates Spring Cloud Starters to 4.1.5
Updates Spring Cloud Function to 4.1.4
Updates Spring Cloud Stream to 4.1.4
Updates Groovy to 4.0.24
Removes spring-integration-aws.version property now manage in Spring Functions Catalog Removes json-path.version as it is managed in Spring Boot dependencies.
Removes Jetbrains `@NotNull` from a Test class.
See #584
=> Update Spring Boot to 3.3.6 and bump other dependencies

applications/stream-applications-core/pom.xml
Updates Prometheus Rsocket Proxy to 1.5.3
=> Use latest release of Prometheus Rsocket Proxy 1.5.3

spring-cloud-dataflow-apps-plugin/pom.xml, stream-applications-build/pom.xml
This commit updates Spring Boot to 3.3.7 and Spring Framework to 6.1.16
in preparation for the 2024.0.1 release.
Resolves #597
=> Update to Spring Boot 3.3.7

stream-applications-build/pom.xml
This commit overrides the `spring-cloud-function` version manged by `spring-cloud-dependencies` from `4.2.0` to `4.2.1-SNAPSHOT` in order to pickup spring-cloud/spring-cloud-function#1224 which brings the fix for functions declared as `FactoryBean`.
See #599
=> Override Spring Cloud Function version

applications/stream-applications-core/pom.xml
Replaces the `micrometer.io:micrometer-registry-prometheus-simpleclient` with `micrometer.io:micrometer-registry-prometheus`.
Also updates the Prometheus RSocket version from `1.5.3` to `2.0.0-M4`.
=> Use new Prometheus RSocket client

spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/main/java/org/springframework/cloud/dataflow/app/plugin/SpringCloudStreamAppGeneratorMojo.java, spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/main/resources/template/app-pom.xml, spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/java/org/springframework/cloud/dataflow/app/plugin/SpringCloudStreamAppGeneratorMojoTest.java
The recent JIB removal broke the Spring Boot plugin config generation due to a Mustache complication with nested sections. This fixes that by ensuring that the `<image>` configuration is always present regardless of what the user configures.
=> [Apps Plugin] Fix Spring Boot plugin config

applications/stream-applications-core/pom.xml
Since there is not a GA version of prometheus-rsocket-proxy 2.0.0 available, this downgrades back to the simpleclient and version 1.5.3
=> Downgrade to prometheus-rsocket-proxy 1.5.3

stream-applications-release-train/stream-applications-descriptor/pom.xml
This updates `org.codehaus.groovy:groovy-all` used by the `stream-applications-release-train` module to `3.0.23` to fix `CVE-2022-4065` from transitive depepdency
`org.testng:testng`.
=> Update Groovy to 3.0.23

applications/stream-applications-core/pom.xml
This updates the generated apps to use the override version of `spring-cloud-function` to `4.2.1`.
=> Update apps to use spring-cloud-function 4.2.1

applications/stream-applications-core/pom.xml
This updates the generated apps to use the override version of `spring-cloud-function` to `4.2.1`. The previous commit was not sufficient as the `<dependencyManagement>` needed to be specified on the apps generated pom.xml
=> Update apps to use spring-cloud-function 4.2.1 (take 2)
