spring-cloud/stream-applications

applications/sink/ftp-sink/README.adoc
applications/sink/ftp-sink/pom.xml
applications/sink/ftp-sink/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
applications/sink/pom.xml
functions/common/ftp-common/pom.xml
functions/common/ftp-common/src/main/java/org/springframework/cloud/fn/common/ftp/FtpSessionFactoryConfiguration.java
functions/common/ftp-common/src/main/java/org/springframework/cloud/fn/common/ftp/FtpSessionFactoryProperties.java
functions/common/function-test-support/pom.xml
functions/common/function-test-support/src/main/java/org/springframework/cloud/fn/test/support/file/remote/RemoteFileTestSupport.java
functions/common/function-test-support/src/main/java/org/springframework/cloud/fn/test/support/ftp/FtpTestSupport.java
functions/consumer/ftp-consumer/pom.xml
functions/consumer/ftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/ftp/FtpConsumerConfiguration.java
functions/consumer/ftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/ftp/FtpConsumerProperties.java
functions/consumer/ftp-consumer/src/test/java/org/springframework/cloud/fn/consumer/ftp/FtpConsumerPropertiesTests.java
functions/consumer/ftp-consumer/src/test/java/org/springframework/cloud/fn/consumer/ftp/FtpConsumerTests.java
functions/pom.xml

Resolves https://github.com/spring-cloud/stream-applications/issues/28

FTP consumer/sink

---

applications/sink/pom.xml
applications/sink/sftp-sink/README.adoc
applications/sink/sftp-sink/pom.xml
applications/sink/sftp-sink/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
functions/common/function-test-support/src/main/java/org/springframework/cloud/fn/test/support/sftp/SftpTestSupport.java
functions/consumer/sftp-consumer/pom.xml
functions/consumer/sftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerConfiguration.java
functions/consumer/sftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerProperties.java
functions/consumer/sftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerSessionFactoryConfiguration.java
functions/consumer/sftp-consumer/src/test/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerPropertiesTests.java
functions/consumer/sftp-consumer/src/test/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerTests.java
functions/pom.xml

Merge only after: https://github.com/spring-cloud/stream-applications/pull/31

SFTP consumer sink

---

applications/source/pom.xml
applications/source/tcp-source/README.adoc
applications/source/tcp-source/pom.xml
applications/source/tcp-source/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
applications/source/tcp-source/src/test/java/org/springframework/cloud/stream/app/source/tcp/TcpSourceTests.java
functions/common/tcp-common/pom.xml
functions/common/tcp-common/src/main/java/org/springframework/cloud/fn/common/tcp/EncoderDecoderFactoryBean.java
functions/common/tcp-common/src/main/java/org/springframework/cloud/fn/common/tcp/Encoding.java
functions/common/tcp-common/src/main/java/org/springframework/cloud/fn/common/tcp/TcpConnectionFactoryProperties.java
functions/pom.xml
functions/supplier/tcp-supplier/pom.xml
functions/supplier/tcp-supplier/src/main/java/org/springframework/cloud/fn/supplier/tcp/TcpSupplierConfiguration.java
functions/supplier/tcp-supplier/src/main/java/org/springframework/cloud/fn/supplier/tcp/TcpSupplierProperties.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/AbstractTcpSupplierTests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/CRLFTests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/L1Tests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/L2Tests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/L4Tests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/LFTests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/NULLTests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/NotNioTests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/PropertiesPopulatedTests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/RAWTests.java
functions/supplier/tcp-supplier/src/test/java/org/springframework/cloud/fn/supplier/tcp/STXETXTests.java

Resolves https://github.com/spring-cloud/stream-applications/issues/43

TCP Supplier/Source

---

applications/source/load-generator-source/README.adoc
applications/source/load-generator-source/pom.xml
applications/source/load-generator-source/src/main/java/org/springframework/cloud/stream/app/source/load/generator/LoadGeneratorSourceConfiguration.java
applications/source/load-generator-source/src/main/java/org/springframework/cloud/stream/app/source/load/generator/LoadGeneratorSourceProperties.java
applications/source/load-generator-source/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
applications/source/load-generator-source/src/test/java/org/springframework/cloud/stream/app/source/load/generator/LoadGeneratorSourceTests.java
applications/source/pom.xml

Resolves https://github.com/spring-cloud/stream-applications/issues/24

Migrate load-generator source

---

applications/source/mqtt-source/README.adoc
applications/source/mqtt-source/pom.xml
applications/source/mqtt-source/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
applications/source/mqtt-source/src/test/java/org/springframework/cloud/stream/app/source/mqtt/MqttSourceTests.java
applications/source/pom.xml
functions/common/mqtt-common/pom.xml
functions/common/mqtt-common/src/main/java/org/springframework/cloud/fn/common/mqtt/MqttConfiguration.java
functions/common/mqtt-common/src/main/java/org/springframework/cloud/fn/common/mqtt/MqttProperties.java
functions/pom.xml
functions/supplier/mqtt-supplier/pom.xml
functions/supplier/mqtt-supplier/src/main/java/org/springframework/cloud/fn/supplier/mqtt/MqttSupplierConfiguration.java
functions/supplier/mqtt-supplier/src/main/java/org/springframework/cloud/fn/supplier/mqtt/MqttSupplierProperties.java
functions/supplier/mqtt-supplier/src/test/java/org/springframework/cloud/fn/supplier/mqtt/MqttSupplierTests.java

Resolves https://github.com/spring-cloud/stream-applications/issues/38

MQTT source as supplier/source

---

README.adoc
functions/supplier/file-supplier/README.adoc
functions/supplier/http-supplier/README.adoc
functions/supplier/jdbc-supplier/README.adoc
functions/supplier/mongodb-supplier/README.adoc
functions/supplier/mqtt-supplier/README.adoc
functions/supplier/tcp-supplier/README.adoc
functions/supplier/time-supplier/README.adoc

Resolves https://github.com/spring-cloud/stream-applications/issues/14
Resolves https://github.com/spring-cloud/stream-applications/issues/18
Resolves https://github.com/spring-cloud/stream-applications/issues/10
Resolves https://github.com/spring-cloud/stream-applications/issues/8

Adding REAMDE for all the supplier modules.

---

functions/common/aws-s3-common/src/main/java/org/springframework/cloud/fn/common/aws/s3/AutoConfigurationExclusionEnvironmentPostProcessor.java
functions/common/aws-s3-common/src/main/resources/META-INF/spring.factories
functions/common/aws-s3-common/src/main/resources/application.properties
functions/common/aws-s3-common/src/test/java/org/springframework/cloud/fn/common/aws/s3/AutoConfigurationExclusionEnvironmentPostProcessorTests.java

Related to issue https://github.com/spring-cloud/stream-applications/issues/75

Fix disabling of auto configured AmazonS3 client

---

applications/sink/jdbc-sink/README.adoc
functions/consumer/jdbc-consumer/pom.xml
functions/supplier/jdbc-supplier/pom.xml

Adds OSS JDBC drivers to jdbc-consumer and jdbc-supplier

Add drivers to jdbc fns

---

applications/source/pom.xml
applications/source/syslog-source/README.adoc
applications/source/syslog-source/pom.xml
applications/source/syslog-source/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
applications/source/syslog-source/src/main/resources/META-INF/dataflow-configuration-metadata.properties
applications/source/syslog-source/src/test/java/org/springframework/cloud/stream/app/source/syslog/SyslogSourceTests.java
functions/function-dependencies/pom.xml
functions/pom.xml
functions/supplier/syslog-supplier/README.adoc
functions/supplier/syslog-supplier/pom.xml
functions/supplier/syslog-supplier/src/main/java/org/springframework/cloud/fn/supplier/syslog/SyslogSupplierConfiguration.java
functions/supplier/syslog-supplier/src/main/java/org/springframework/cloud/fn/supplier/syslog/SyslogSupplierProperties.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/AbstractSyslogSupplierTests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/NotNioTests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/PropertiesPopulatedTests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/Tcp3164Tests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/Tcp5424Tests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/TcpAndUdp3164Tests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/TcpAndUdp5424Tests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/Udp3164Tests.java
functions/supplier/syslog-supplier/src/test/java/org/springframework/cloud/fn/supplier/syslog/Udp5424Tests.java

- Provide TCP/UDP based syslog supplier and then generate apps based on that

Syslog supplier/source

---

README.adoc
functions/consumer/zeromq-consumer/README.adoc
functions/consumer/zeromq-consumer/pom.xml
functions/consumer/zeromq-consumer/src/main/java/org/springframework/cloud/fn/consumer/zeromq/ZeroMqConsumerConfiguration.java
functions/consumer/zeromq-consumer/src/main/java/org/springframework/cloud/fn/consumer/zeromq/ZeroMqConsumerProperties.java
functions/consumer/zeromq-consumer/src/test/java/org/springframework/cloud/fn/consumer/zeromq/ZeroMqConsumerConfigurationTests.java
functions/pom.xml
functions/supplier/zeromq-supplier/README.adoc

add zeromq consumer configuration, module and documentation

---

applications/source/mongodb-source/README.adoc
functions/supplier/mongodb-supplier/README.adoc
functions/supplier/mongodb-supplier/pom.xml
functions/supplier/mongodb-supplier/src/main/java/org/springframework/cloud/fn/supplier/mongo/MongodbSupplierConfiguration.java
functions/supplier/mongodb-supplier/src/main/java/org/springframework/cloud/fn/supplier/mongo/MongodbSupplierProperties.java
functions/supplier/mongodb-supplier/src/main/java/org/springframework/cloud/fn/supplier/mongo/UpdatingMongoDbMessageSource.java
functions/supplier/mongodb-supplier/src/test/java/org/springframework/cloud/fn/supplier/mongo/MongodbSupplierApplicationTests.java

Fixes https://github.com/spring-cloud/stream-applications/issues/143

GH-143: Add an update option to MongoDB Supplier

---

applications/sink/rabbit-sink/README.adoc
applications/sink/rabbit-sink/src/test/java/org/springframework/cloud/stream/app/sink/rabbit/HeadersMappedLastTest.java
applications/sink/rabbit-sink/src/test/java/org/springframework/cloud/stream/app/sink/rabbit/HeadersMappedLastTests.java
functions/consumer/rabbit-consumer/src/main/java/org/springframework/cloud/fn/consumer/rabbit/RabbitConsumerConfiguration.java
functions/consumer/rabbit-consumer/src/main/java/org/springframework/cloud/fn/consumer/rabbit/RabbitConsumerProperties.java

Add the possibilities to configure the headersMappedLast for the RabbitMQ consumer

---

applications/source/websocket-source/src/test/java/org/springframework/cloud/stream/app/source/websocket/WebsocketSourceTests.java
functions/supplier/websocket-supplier/src/test/java/org/springframework/cloud/fn/supplier/websocket/WebsocketSupplierTests.java

Related to: https://github.com/spring-cloud/stream-applications/issues/171

GH-171: Fix WebSocket tests for upstream changes

---

applications/sink/router-sink/README.adoc

Resolves #191
@pivotal-cla This is an Obvious Fix

Fixed broken link in router-sink README.adoc

---

functions/common/cdc-debezium-boot-starter/src/test/java/org/springframework/cloud/fn/common/cdc/CdcBootStarterIntegrationTest.java

jdk8_301 TLS12 jdbc handling

---

applications/sink/rabbit-sink/src/test/java/org/springframework/cloud/stream/app/sink/rabbit/OwnConnectionTest.java

* Check boot connection factory destroyed earlier in test
* Check rabbit template not using boot connection factory
Explanation inline  in PR

Fix rabbit sink IT OwnConnectionTest

---

applications/stream-applications-integration-tests/src/test/resources/geode-test/Dockerfile
functions/function/aggregator-function/pom.xml
stream-applications-build/pom.xml

* Fix Geode integration tests
* Upgrade spring-geode-starter -> 1.6.3
* Upgrade apachegeode/geode -> 1.14.3

Upgrade Geode to support Spring Boot 2.6.3

---

functions/supplier/sftp-supplier/src/main/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierConfiguration.java

The `Flux.doOnSubscribe()` happens really before the actual subscription is set to the `Publisher`.
So, there is possible a race condition when we start producing messages, but `FluxMessageChannel`
didn't get the actual subscriber to process.
**Cherry-pick to `2021.1.x` & `2020.0.x`**

Change SFTP reactive init to doOnRequest

---

applications/stream-applications-integration-tests/src/test/java/org/springframework/cloud/stream/app/integration/test/sink/log/KafkaLogSinkActuatorAuthTests.java
applications/stream-applications-integration-tests/src/test/java/org/springframework/cloud/stream/app/integration/test/sink/log/LogSinkActuatorAuthTests.java
applications/stream-applications-integration-tests/src/test/java/org/springframework/cloud/stream/app/integration/test/sink/log/RabbitMQLogSinkActuatorAuthTests.java
applications/stream-applications-integration-tests/src/test/java/org/springframework/cloud/stream/app/integration/test/source/time/TimeSourceTests.java

Don't merge until the latest 3.2.0-SS app images with security changes are published

Add actuator auth tests

---

applications/source/sftp-source/README.adoc

Old:
--ftp.supplier.factory.username=user --sftp.supplier.factory.password=pw
New:
--sftp.supplier.factory.username=user --sftp.supplier.factory.password=pw

Change ftp by sftp

---

src/main/groovy/org/springframework/jenkins/stream/applications/ci/StreamApplicationsBuildMaker.groovy

While investigating the possible move to Harbor for our Docker images, I noticed that the jib:build was not doing retries. The reason is that the jib maven plugin is not a good actor and for uncaught exceptions it does not return a valid exit code. The exit code is still `0` for runtime exceptions. 
These change the handling to grep the output from the command for `BUILD FAILURE`. Trust me, I looked for a cleaner, less brittle approach but this is the one that worked. I have tested all possible scenarios locally and this will at least help us when the `jib:build` fails due to timeout or some other internal error. 
To see an actual instance of this script look here https://jenkins.spring.io/job/stream-applications-sftp-source-main-ci/
As for the concern of rate limiting we can discuss …

Fix jib:build retry in generated jenkins app build scripts

---

applications/source/file-source/README.adoc
applications/source/http-source/pom.xml
applications/source/mail-source/src/test/java/org/springframework/cloud/stream/app/source/file/MailSourceTests.java
applications/stream-applications-core/pom.xml
applications/stream-applications-core/stream-applications-composite-function-support/pom.xml
applications/stream-applications-core/stream-applications-micrometer-common/pom.xml
applications/stream-applications-core/stream-applications-postprocessor-common/pom.xml
applications/stream-applications-core/stream-applications-security-common/pom.xml
applications/stream-applications-core/stream-applications-test-support/pom.xml
functions/common/cdc-debezium-common/src/main/java/org/springframework/cloud/fn/common/cdc/EmbeddedEngine.java
functions/function-dependencies/pom.xml
functions/spring-functions-parent/pom.xml
stream-applications-build/pom.xml

GH-268: Update libs to latest patch versions

---

applications/stream-applications-core/pom.xml
functions/function/twitter-function/pom.xml
stream-applications-build/pom.xml

GH-272: Update to Spring Boot 2.6.8

---

applications/source/file-source/pom.xml

I'm going to merge this so I can see if it fixes the CI build as I am unable to repro this locally.

Fix CI build - can't find app generator plugin

---

applications/stream-applications-core/pom.xml

This updates the apps plugin to the newly released version. 
⚠️ **DO NOT MERGE YET** as we seem to be having problems releasing the plugin

Update apps plugin to 1.0.7

---

applications/sink/elasticsearch-sink/README.adoc

Fix typo for elasticsearch-sink README

Fix typo for elasticsearch-sink README

---

applications/processor/http-request-processor/README.adoc
applications/processor/http-request-processor/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
applications/processor/http-request-processor/src/main/resources/META-INF/dataflow-configuration-metadata.properties
functions/function/http-request-function/src/main/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionConfiguration.java
functions/function/http-request-function/src/main/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionProperties.java

Revise HttpRequestFunctionConfiguration configuration

---

functions/supplier/cdc-debezium-supplier/README.adoc

1. fix `MetadataStore` link format
2. fix `CdcSupplierProperties.java` link

Fix cdc-debezium-supplier README.adoc

---

local/README.md
local/create-containers.sh
local/download-apps.sh

Updated to add filter for download, create-container will skip when the jar isn't present.

Updated to add filter 

---

functions/common/aws-s3-common/pom.xml
functions/consumer/s3-consumer/src/test/java/org/springframework/cloud/fn/consumer/s3/AmazonS3UploadFileTests.java
functions/consumer/s3-consumer/src/test/java/org/springframework/cloud/fn/consumer/s3/AmazonS3UploadInputStreamTests.java
functions/consumer/sftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerSessionFactoryConfiguration.java

* Fix SftpConsumerConfiguration knownHosts issue
* Disable AWS S3 tests

[SB3 Update] SftpConsumer + AWS S3 

---

applications/source/jdbc-source/README.adoc
applications/stream-applications-core/stream-applications-test-support/pom.xml
functions/supplier/jms-supplier/pom.xml

This PR holds several commits (each one a specific area/fix) towards the goal of being able to run `./mvnw clean install` in the repo.
I was going to make N PRs but the toil outweighed the benefit. Each commit holds a specific "fix" or "change" though. Please take a scan and we can adjust in retrospect. Thanks.

[SB3 Update] more fixes towards unit tests

---

.github/workflows/common.yml
.settings.xml
build-app.sh
build-core.sh

[SB3 Build] Ensure apps are trying to build.

build app containers

---

local/README.md
local/pack-containers.sh

Add script that uses pack to create a container from a downloaded application jar.
Provides a way to resolve. [Issue#5040](https://github.com/spring-cloud/spring-cloud-dataflow/issues/5040)

Add script that uses pack to create a container

---

functions/consumer/cassandra-consumer/README.adoc
functions/consumer/cassandra-consumer/pom.xml
functions/consumer/cassandra-consumer/src/main/java/org/springframework/cloud/fn/consumer/cassandra/CassandraConsumerConfiguration.java
functions/consumer/cassandra-consumer/src/main/java/org/springframework/cloud/fn/consumer/cassandra/cluster/CassandraAppClusterConfiguration.java
functions/consumer/cassandra-consumer/src/test/java/org/springframework/cloud/fn/consumer/cassandra/CassandraConsumerApplicationTests.java
functions/consumer/cassandra-consumer/src/test/java/org/springframework/cloud/fn/consumer/cassandra/CassandraContainerTest.java
functions/consumer/cassandra-consumer/src/test/java/org/springframework/cloud/fn/consumer/cassandra/CassandraEntityInsertTests.java
functions/consumer/cassandra-consumer/src/test/java/org/springframework/cloud/fn/consumer/cassandra/CassandraIngestInsertTests.java
functions/consumer/cassandra-consumer/src/test/java/org/springframework/cloud/fn/consumer/cassandra/CassandraIngestNamedParamsTests.java
functions/consumer/cassandra-consumer/src/test/java/org/springframework/cloud/fn/consumer/cassandra/CassandraIngestUpdateTests.java
functions/consumer/cassandra-consumer/src/test/java/org/springframework/cloud/fn/consumer/cassandra/domain/Book.java

Fixes https://github.com/spring-cloud/stream-applications/issues/350
* Use Testcontainers for Cassandra
* Adjust components code style a bit
* Convert `Book` testing entity to the `record`
* Use `@DynamicPropertySource` to expose Docker ENV to Spring Boot configuration properties

GH-350: Upgrade SI Cassandra; re-enable tests

---

.github/workflows/ci-pr.yml
functions/function/http-request-function/src/main/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionConfiguration.java
functions/function/http-request-function/src/test/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionTestApplicationTests.java

[Issues] Change http-request to non-reactive

---

functions/supplier/xmpp-supplier/src/test/java/org/springframework/cloud/fn/supplier/xmpp/XmppSupplierConfigurationTests.java

updated configuration for consistency with other, similar, tests

update test configuration for consistency

---

README.adoc
applications/source/pom.xml
applications/source/xmpp-source/README.adoc
applications/source/xmpp-source/pom.xml
applications/source/xmpp-source/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
applications/source/xmpp-source/src/main/resources/META-INF/dataflow-configuration-metadata.properties
applications/source/xmpp-source/src/test/java/org/springframework/cloud/stream/app/source/xmpp/XmppSourceInvalidConfigTests.java
applications/source/xmpp-source/src/test/java/org/springframework/cloud/stream/app/source/xmpp/XmppSourceTests.java

implement `xmpp-source` application which utilizes the `xmpp-supplier` to receive messages from an XMPP Server

initial commit

---

applications/sink/elasticsearch-sink/pom.xml
applications/sink/elasticsearch-sink/src/test/java/org/springframework/cloud/stream/app/sink/elasticsearch/ElasticsearchSinkTests.java
applications/source/rabbit-source/src/test/java/org/springframework/cloud/stream/app/source/rabbit/RabbitSourceListenerTests.java
functions/consumer/elasticsearch-consumer/pom.xml
functions/consumer/elasticsearch-consumer/src/main/java/org/springframework/cloud/fn/consumer/elasticsearch/ElasticsearchConsumerConfiguration.java
functions/consumer/elasticsearch-consumer/src/test/java/org/springframework/cloud/fn/consumer/elasticsearch/ElasticsearchConsumerApplicationTests.java
stream-applications-build/pom.xml

* Update Boot and Spring versions. 
* Improve Rabbit listener

[SB3] Update Elasticsearch Client.

---

functions/function/object-detection-function/pom.xml
functions/function/object-detection-function/src/main/java/org/springframework/cloud/fn/object/detection/protos/StringIntLabelMapOuterClass.java

Fix protoc usage

---

.github/workflows/ci-pr.yml
functions/function/object-detection-function/pom.xml
functions/spring-functions-parent/pom.xml

Updating protobuf to 3.19.6

---

applications/source/debezium-source/README.adoc

Document how to configure debezium offsets

---

applications/sink/cassandra-sink/README.adoc
applications/sink/redis-sink/README.adoc
stream-applications-build/pom.xml

Update to Spring Boot 3.1.0

---

applications/stream-applications-integration-tests/pom.xml
applications/stream-applications-integration-tests/src/test/java/org/springframework/cloud/stream/app/integration/test/source/s3/S3SourceTests.java

* Update `stream-applications-integration-tests/pom.xml` to rely on versions from the parent
* Use `s3-supplier` as dependency to rely on its transitives for AWS SDK

Update `S3SourceTests` to use AWS SDK v2

---

functions/consumer/ftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/ftp/FtpConsumerConfiguration.java
functions/consumer/jdbc-consumer/src/main/java/org/springframework/cloud/fn/consumer/jdbc/JdbcConsumerConfiguration.java
functions/consumer/log-consumer/src/main/java/org/springframework/cloud/fn/consumer/log/LogConsumerConfiguration.java
functions/consumer/sftp-consumer/src/main/java/org/springframework/cloud/fn/consumer/sftp/SftpConsumerConfiguration.java
functions/supplier/file-supplier/src/main/java/org/springframework/cloud/fn/supplier/file/FileSupplierConfiguration.java
functions/supplier/ftp-supplier/src/main/java/org/springframework/cloud/fn/supplier/ftp/FtpSupplierConfiguration.java
functions/supplier/http-supplier/src/main/java/org/springframework/cloud/fn/supplier/http/HttpSupplierConfiguration.java
functions/supplier/jms-supplier/src/main/java/org/springframework/cloud/fn/supplier/jms/JmsSupplierConfiguration.java
functions/supplier/mqtt-supplier/src/main/java/org/springframework/cloud/fn/supplier/mqtt/MqttSupplierConfiguration.java
functions/supplier/rabbit-supplier/src/main/java/org/springframework/cloud/fn/supplier/rabbit/RabbitSupplierConfiguration.java
functions/supplier/sftp-supplier/src/main/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierConfiguration.java
functions/supplier/tcp-supplier/src/main/java/org/springframework/cloud/fn/supplier/tcp/TcpSupplierConfiguration.java
functions/supplier/websocket-supplier/src/main/java/org/springframework/cloud/fn/supplier/websocket/WebsocketSupplierConfiguration.java

- Remove the usage of deprecated IntegrationFlows in favor of IntegrationFlow

Address deprecation warnings

---

stream-applications-build/pom.xml

Update to Spring Boot 3.1.4

---

applications/processor/aggregator-processor/README.adoc
applications/sink/jdbc-sink/README.adoc
applications/sink/mongodb-sink/README.adoc
applications/sink/redis-sink/README.adoc
applications/sink/s3-sink/README.adoc
applications/sink/throughput-sink/README.adoc
applications/source/mail-source/README.adoc
applications/source/mongodb-source/README.adoc
applications/source/s3-source/README.adoc
stream-applications-build/pom.xml

* Also update to Spring Cloud Stream 4.0.4

Update to Spring Cloud 2022.0.4

---

.github/workflows/apps-plugin-release.yml

See spring-cloud/spring-cloud-dataflow#5584

Use new private release repo libs-release-staging

---

stream-applications-build/pom.xml

Latests Boot 3.1.x and related.

Updated dependency versions.

---

update-project-version.sh
versions.json

Release 2024.0.0-M1.

---

applications/stream-applications-core/pom.xml

In preparation for the `2024.0.0` release...

Update to Spring Functions Catalog 5.0.0

---

spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-metadata-plugin/src/main/java/org/springframework/cloud/dataflow/app/plugin/MetadataAggregationMojo.java

Improving on the previous commit, this adds a set of expected problematic enum classes and only continues processing when an enum is unable to load if the enum is in the list.

[Apps Plugin] Allow bad enum constants (take 2)

---

.github/workflows/common.yml

Removes the extra github-token not required in setup_java@v4.

Fix common CI workflow

---

.github/workflows/common.yml

Added enviromental variables with multiple trivy repos.

Provide alternative Trivy repo

---

.github/workflows/common.yml

Added scan job for Trivy and removed individual trivy scans for all application jobs.

Move Trivy to single job

---

.github/actions/install-trivy/action.yml
.github/workflows/apps-plugin-milestone.yml
.github/workflows/apps-plugin-next-dev-version.yml
.github/workflows/apps-plugin-release.yml
.github/workflows/apps-plugin-snapshot.yml
.github/workflows/cental-sync-create.yml
.github/workflows/ci-2022-0-x.yml
.github/workflows/ci-it.yml
.github/workflows/ci-main.yml
.github/workflows/common.yml
.github/workflows/descriptor.yml

Update 2022.0.x workflows to match main.

Ensure workflows for 2022.0.x is same as main

---

.github/workflows/ci-pr.yml

Added enviromental variables with multiple trivy repos. Restore scan after build.

Restore scan in CI-PR and Provide alternative Trivy repo.

---

.github/actions/install-trivy/action.yml
.github/workflows/ci-pr.yml
scan-folders.sh
scan-jar.sh
scan-jars.sh

Added enviromental variables with multiple trivy repos. Reverts scan after build.
Backported scan folders from main.

Revert scan in CI-PR and Provide alternative Trivy repo

---

create-matrices.sh

Ensure that matrix generation for modules ignore function paths moved to spring functions catalog.
Added checks for presence of folders when generating module matrix.

Ensure that matrix generation for modules ignore function paths

---

update-project-version.sh

Fixes update-project-version.sh for latests version plugin. [skip ci]

Fix update-project-version.sh to same as 2022.0.x

---

.github/workflows/common.yml

Updates JFROG_CLI_BUILD_NAME and JFROG_CLI_BUILD_NUMBER from input to workflow.

Fix build-name / number from input.

---

applications/stream-applications-core/pom.xml

This commit updates to the latest version of the apps generator plugin `1.1.0-SNAPSHOT`.

[WAIT-FOR-BRANCH] Update to latest version of apps plugin

---

.github/dco.yml
stream-applications-release-train/stream-applications-docs/src/main/asciidoc/contributing.adoc

⚠️ DO NOT MERGE ⚠️ Update from CLA to DCO (main)

---

.github/dco.yml
stream-applications-release-train/stream-applications-docs/src/main/asciidoc/contributing.adoc

Update from CLA to DCO (2022.0.x)

---

.github/dco.yml
stream-applications-release-train/stream-applications-docs/src/main/asciidoc/contributing.adoc

Update from CLA to DCO (2024.0.x)

---

spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/main/java/org/springframework/cloud/dataflow/app/plugin/MavenXmlWriter.java
spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/main/resources/template/app-pom.xml
spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/main/resources/template/apps-modules-pom.xml
spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/java/org/springframework/cloud/dataflow/app/plugin/MojoHarnessTest.java
spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/java/org/springframework/cloud/dataflow/app/plugin/SpringCloudStreamAppGeneratorMojoTest.java
spring-cloud-dataflow-apps-plugin/spring-cloud-dataflow-apps-generator-plugin/src/test/resources/unit/http-source-apps/pom.xml

Removes the JIB pluigin from the apps metadata plugin.

[Apps Plugin] Remove JIB plugin
